name = "Pixelmon"
author = "luke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0adf88278695ec093f12ad2ecd95da6bb05dd9414b47f9d34bdeef4d904914b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
