name = "Pixelmon"
author = "luke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe11fff17cbc9d7a7d40a0233e81e262a995dc28c49f2b296b5aa09c6fdcf3c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
