name = "Pixelmon"
author = "luke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5999cc00ddc25bf44dd437d525621c8133c6e169c3051c0f73d423f7ba9a0f28"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
